name: Fortify Scan
on: [push, pull_request]

jobs:
  fortify_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Pull Fortify Docker Image
        run: docker pull fortifydocker/fortify-ci-tools

      - name: Run Fortify Scan
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/workspace \
            fortifydocker/fortify-ci-tools \
            scan --source /workspace --build-id ${{ github.run_id }}
