name: Pull and Run Docker Image

on:
  workflow_dispatch:  # Allows manual triggering of the workflow from the Actions tab
  push: 
    branches: 
      - main

jobs:
  pull_and_run:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      # Step 3: Pull the Docker image
      - name: Pull Docker image
        run: docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/fortify-image

      # Step 4: Run the Docker container
      - name: Run Docker container
        run: docker run -dt narmadutlla/fortify-image

      # Step 5: Verify the Docker container is running
      - name: List running Docker containers
        run: docker ps
